# pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: fresh-app
  labels:
    app: fresh-app
spec:
  containers:
  - name: fresh-app
    image: BillTestContainerRegistry.azurecr.io/fresh-app:latest
    resources:
      limits:
        memory: "1Gi"
        cpu: "1"
    ports:
      - containerPort: 80